<MyScreenManager>:
    id: screen_manager
    IntroScreen:
        id: intro_screen
        name: "intro_screen"
        manager: screen_manager
    FirstUseScreen:
        id: first_use_screen
        name: "first_use_screen"
        manager: screen_manager
    WalletSetupScreen:
        id: wallet_setup_screen
        name: "wallet_setup_screen"
        manager: screen_manager
    CreateWalletScreen:
        id: create_wallet_screen
        name: "create_wallet_screen"
        manager: screen_manager
    CreateExtraWalletScreen:
        id: create_extrawallet_screen
        name: "create_extrawallet_screen"
        manager: screen_manager
    ImportKeysScreen:
        id: importkeys_screen
        name: "importkeys_screen"
        manager: screen_manager
    ImportExtraKeysScreen:
        id: importextrakeys_screen
        name: "importextrakeys_screen"
        manager: screen_manager
    WalletScreen:
        id: wallet_screen
        name: "wallet_screen"
        manager: screen_manager
    SendXRPScreen
        id: sendxrp_screen
        name: "sendxrp_screen"
        manager: screen_manager
    SendLipisaScreen
        id: sendlipisa_screen
        name: "sendlipisa_screen"
        manager: screen_manager
    SendCalorieTestScreen
        id: sendcalorietest_screen
        name: "sendcalorietest_screen"
        manager: screen_manager
    LoginScreen:
        id: login_screen
        name: "login_screen"
        manager: screen_manager
    NFTMintScreen:
        id: nftmint_screen
        name: "nftmint_screen"
        manager: screen_manager
    CreateImportWalletScreen:
        id: createimportwallet_screen
        name: "createimportwallet_screen"
        manager: screen_manager
    DEXTradeScreen:
        id: dextrade_screen
        name: "dextrade_screen"
        manager: screen_manager
    FoodTrackScreen:
        id: foodtrack_screen
        name: "foodtrack_screen"
        manager: screen_manager
    SettingsScreen:
        id: settings_screen
        name: "settings_screen"
        manager: screen_manager

<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: "#dadeed"
    text_color: "#4a4939"
    icon_color: "#008D36"
    ripple_color: "#c5bdd2"
    selected_color: "#4a4939"
<DrawerLabelItem@MDNavigationDrawerItem>
    text_color: "#4a4939"
    icon_color: "#4a4939"
    focus_behavior: False
    selected_color: "#4a4939"
    _no_ripple_effect: True

<WalletScreen>:

    xrp_address: xrp_address
    xrp_balance: xrp_balance
    lipisa_balance: lipisa_balance
    calorietest_balance: calorietest_balance
    transaction1: transaction1
    transaction2: transaction2
    transaction3: transaction3
    transaction4: transaction4
    transaction5: transaction5
    transaction6: transaction6
    transaction7: transaction7
    transaction8: transaction8
    transaction9: transaction9
    transaction10: transaction10
    transaction11: transaction11
    transaction12: transaction12
    transaction13: transaction13
    transaction14: transaction14
    transaction15: transaction15
    transaction16: transaction16
    transaction17: transaction17
    transaction18: transaction18
    transaction19: transaction19
    transaction20: transaction20

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDGridLayout:
                size_hint: (1, .1)
                cols:4

                MDLabel:
                    size_hint: (.2, 1)

                MDGridLayout:
                    size_hint: (.05, 1)
                    rows:3
                    MDLabel:
                        size_hint: (1, .2)
                    MDIcon:
                        icon: "wallet"
                        theme_text_color: "Custom"
                        text_color: rgba('#008D36')
                        icon_size: "16sp"
                        size_hint: (1, .6)
                    MDLabel:
                        size_hint: (1, .2)
                MDLabel:
                    size_hint: (.50, 1)
                    text: "XRPL wallet"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_size: '22sp'
                MDLabel:
                    size_hint: (.25, 1)
            MDGridLayout:
                size_hint: (1, .11)
                rows:3
                MDLabel:
                    size_hint_x: 0.2
                    size_hint_y: 0.2
                MDLabel:
                    size_hint_x: 0.75
                    size_hint_y: 0.2
                MDLabel:
                    size_hint_x: 0.05
                    size_hint_y: 0.2
                MDLabel:
                    text: "Address"
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    font_style: "Body1"
                    font_size: 11
                    size_hint_x: 0.08
                    size_hint_y: 0.6
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size

                MDFlatButton
                    id: xrp_address
                    font_style: "Body1"
                    size_hint_x: 0.75
                    size_hint_y: 0.6
                    font_size: 10.5
                    halign: "center"
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release: app.root.get_screen('wallet_screen').menu_open(self)

                MDBoxLayout:
                    size_hint_x: 0.17
                    size_hint_y: 0.6
                    md_bg_color: rgba('#c9cfe5')
                    MDIconButton:
                        icon: "content-copy"
                        icon_size: "16sp"
                        theme_icon_color: "Custom"
                        text_color: rgba('#f9b233')
                        pos_hint: {"center_x": .5, "center_y": .5}
                        on_release: root.copy_address()
                MDLabel:
                    size_hint_x: 0.2
                    size_hint_y: 0.2
                MDLabel:
                    size_hint_x: 0.75
                    size_hint_y: 0.2
                MDLabel:
                    size_hint_x: 0.05
                    size_hint_y: 0.2
            MDGridLayout:
                size_hint: (1, .2)
                cols:5
                rows:3

                MDLabel:
                    size_hint: (.25, 1)
                    text: "XRP"
                    halign: "center"
                    font_size: 11
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.48, 1)
                    id: xrp_balance
                    font_style: "Body1"
                    font_size: 11
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: rgba('#008D36')
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "send"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#505CA9')
                    on_press: root.send_xrp_screen()
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "arrow-left-right-bold-outline"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#008D36')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.09, 1)
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.25, 1)
                    text: "Lipisa"
                    halign: "center"
                    font_size: 11
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.48, 1)
                    id: lipisa_balance
                    font_style: "Body1"
                    font_size: 11
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: rgba('#008D36')
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "send"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#505CA9')
                    on_press: root.send_lipisa_screen()
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "arrow-left-right-bold-outline"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#008D36')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "timeline-check"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#f9b233')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_press: root.open_dialog_lipisa()

                MDLabel:
                    size_hint: (.25, 1)
                    text: "CalorieTest"
                    halign: "center"
                    font_size: 11
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.48, 1)
                    id: calorietest_balance
                    font_style: "Body1"
                    font_size: 11
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: rgba('#008D36')
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "send"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#505CA9')
                    on_press: root.send_calorietest_screen()
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "arrow-left-right-bold-outline"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#008D36')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDIconButton:
                    size_hint: (.09, 1)
                    icon: "timeline-check"
                    icon_size: "16sp"
                    theme_icon_color: "Custom"
                    text_color: rgba('#f9b233')
                    canvas.before:
                        Color:
                            rgba: rgba('#c9cfe5')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_press: root.open_dialog_calorietest()

            MDLabel:
                size_hint: (1, .05)
                text: "Transactions"
                halign: "center"
                font_size: 12
                theme_text_color: "Primary"
            MDScrollView:
                size_hint: (1, .26)
                do_scroll_x: False
                do_scroll_y: True
                bar_color: rgba ('#f9b233')
                MDGridLayout:
                    cols: 1
                    padding: 10
                    spacing: 25
                    size_hint: None, None
                    width: 500
                    height: self.minimum_height
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction1
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction2
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction3
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction4
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction5
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction6
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction7
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction8
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction9
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction10
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction11
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction12
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction13
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction14
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction15
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction16
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction17
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction18
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction19
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction20
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        text: "Transactions: 21"
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        text: "Transactions: 22"
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        text: "Transactions: 23"
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        text: "Transactions: 24"
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        text: "Transactions: 25"
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        text: "Transactions: 26"
                        font_size: 11
                        theme_text_color: "Primary"
            MDLabel:
                size_hint: (1, .18)
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["menu", lambda x: nav_drawer.set_state('toggle')]]
    MDNavigationDrawer:
        md_bg_color: rgba('#b6bedb')
        id: nav_drawer
        radius: (0, 16, 16, 0)

        MDNavigationDrawerMenu:

            MDNavigationDrawerHeader:
                title: "CalorieApp"
                title_color: "#202443"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                icon: "wallet"
                text: "Wallet"
                on_press:
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "brush"
                text: "NFT Minter"
                on_press:
                    root.nftmintscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "wallet-plus"
                text: "Create/Import Wallet"
                on_press:
                    root.createimportwalletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "arrow-left-right-bold-outline"
                text: "DEX Trade"
                on_press:
                    root.dextradescreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "food"
                text: "Food Tracker"
                on_press:
                    root.foodtrackscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "application-settings"
                text: "Settings"
                on_press:
                    root.settingsscreen()
                    nav_drawer.set_state("close")

<SendXRPScreen>
    xrp_address: xrp_address
    xrp_balance: xrp_balance
    amount_input: amount_input
    destination_input: destination_input
    transaction1: transaction1
    transaction2: transaction2
    transaction3: transaction3
    transaction4: transaction4
    transaction5: transaction5
    transaction6: transaction6
    transaction7: transaction7
    transaction8: transaction8
    transaction9: transaction9
    transaction10: transaction10
    transaction11: transaction11
    transaction12: transaction12
    transaction13: transaction13
    transaction14: transaction14
    transaction15: transaction15
    transaction16: transaction16
    transaction17: transaction17
    transaction18: transaction18
    transaction19: transaction19
    transaction20: transaction20

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            BoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Address"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_style: "Body1"
                    font_size: 10
                    size_hint_x: 0.12
                MDLabel:
                    elevation: 3
                    id: xrp_address
                    font_style: "Body1"
                    font_size: 12
                    size_hint_x: 0.88
                    halign: "center"
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: amount_input
                multiline: False
                input_filter: 'float'
                input_filter_min: 0
                input_filter_max: 999999999999.999999
                hint_text: 'Amount (XRP)'
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: destination_input
                multiline: False
                hint_text: 'Destination Address'
            MDLabel:
                size_hint: (1, .1)
            MDGridLayout:
                size_hint: (1, .4)
                cols:3

                MDLabel:
                    size_hint: (.35, 1)
                MDFillRoundFlatIconButton:
                    size_hint: (.3, 1)
                    icon: "send"
                    theme_icon_color: "Custom"
                    icon_color: rgba('#505CA9')
                    text:"Send XRP"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (.6, 1)
                    on_press: root.send_xrp()
                MDLabel:
                    size_hint: (.35, 1)
            MDLabel:
                size_hint: (1, .4)
            MDGridLayout:
                size_hint: (1, .5)
                cols:3

                MDLabel:
                    size_hint: (.22, 1)
                    text: "XRP"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_size: 20
                    theme_text_color: "Primary"
                MDLabel:
                    size_hint: (.56, 1)
                    id: xrp_balance
                    font_style: "Body1"
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: "green"
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.22, 1)
            MDLabel:
                size_hint: (1, .5)
                text: "Transactions"
                halign: "center"
                font_size: 12
                theme_text_color: "Primary"
            MDScrollView:
                size_hint: (1, 2)
                do_scroll_x: False
                do_scroll_y: True
                bar_color: rgba ('#f9b233')
                MDGridLayout:
                    cols: 1
                    padding: 10
                    spacing: 25
                    size_hint: None, None
                    width: 500
                    height: self.minimum_height
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction1
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction2
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction3
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction4
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction5
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction6
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction7
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction8
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction9
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction10
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction11
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction12
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction13
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction14
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction15
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction16
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction17
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction18
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction19
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction20
                        font_size: 11
                        theme_text_color: "Primary"
            MDLabel:
                size_hint: (1, 1.5)
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.backto_wallet()]]

<SendLipisaScreen>
    xrp_address: xrp_address
    lipisa_balance: lipisa_balance
    amount_lipisa_input: amount_lipisa_input
    destination_input: destination_input
    transaction1: transaction1
    transaction2: transaction2
    transaction3: transaction3
    transaction4: transaction4
    transaction5: transaction5
    transaction6: transaction6
    transaction7: transaction7
    transaction8: transaction8
    transaction9: transaction9
    transaction10: transaction10
    transaction11: transaction11
    transaction12: transaction12
    transaction13: transaction13
    transaction14: transaction14
    transaction15: transaction15
    transaction16: transaction16
    transaction17: transaction17
    transaction18: transaction18
    transaction19: transaction19
    transaction20: transaction20

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            BoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Address"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_style: "Body1"
                    font_size: 10
                    size_hint_x: 0.12
                MDLabel:
                    elevation: 3
                    id: xrp_address
                    font_style: "Body1"
                    font_size: 12
                    size_hint_x: 0.88
                    halign: "center"
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: amount_lipisa_input
                multiline: False
                input_filter: 'float'
                input_filter_min: 0
                input_filter_max: 999999999999.999999
                hint_text: 'Amount (Lipisa)'
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: destination_input
                multiline: False
                hint_text: 'Destination Address'
            MDLabel:
                size_hint: (1, .1)
            MDGridLayout:
                size_hint: (1, .4)
                cols:3

                MDLabel:
                    size_hint: (.35, 1)
                MDFillRoundFlatIconButton:
                    size_hint: (.3, 1)
                    icon: "send"
                    theme_icon_color: "Custom"
                    icon_color: rgba('#505CA9')
                    text:"Send Lipisa"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (.6, 1)
                    on_press: root.send_lipisa()
                MDLabel:
                    size_hint: (.35, 1)
            MDLabel:
                size_hint: (1, .4)
            MDGridLayout:
                size_hint: (1, .5)
                cols:3

                MDLabel:
                    size_hint: (.22, 1)
                    text: "Lipisa"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_size: 20
                    theme_text_color: "Primary"
                MDLabel:
                    size_hint: (.56, 1)
                    id: lipisa_balance
                    font_style: "Body1"
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: "green"
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.22, 1)
            MDLabel:
                size_hint: (1, .5)
                text: "Transactions"
                halign: "center"
                font_size: 12
                theme_text_color: "Primary"
            MDScrollView:
                size_hint: (1, 2)
                do_scroll_x: False
                do_scroll_y: True
                bar_color: rgba ('#f9b233')
                MDGridLayout:
                    cols: 1
                    padding: 10
                    spacing: 25
                    size_hint: None, None
                    width: 500
                    height: self.minimum_height
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction1
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction2
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction3
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction4
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction5
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction6
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction7
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction8
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction9
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction10
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction11
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction12
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction13
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction14
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction15
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction16
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction17
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction18
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction19
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction20
                        font_size: 11
                        theme_text_color: "Primary"
            MDLabel:
                size_hint: (1, 1.5)
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.backto_wallet()]]

<SendCalorieTestScreen>
    xrp_address: xrp_address
    calorietest_balance: calorietest_balance
    amount_calorietest_input: amount_calorietest_input
    destination_input: destination_input
    transaction1: transaction1
    transaction2: transaction2
    transaction3: transaction3
    transaction4: transaction4
    transaction5: transaction5
    transaction6: transaction6
    transaction7: transaction7
    transaction8: transaction8
    transaction9: transaction9
    transaction10: transaction10
    transaction11: transaction11
    transaction12: transaction12
    transaction13: transaction13
    transaction14: transaction14
    transaction15: transaction15
    transaction16: transaction16
    transaction17: transaction17
    transaction18: transaction18
    transaction19: transaction19
    transaction20: transaction20

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            BoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Address"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_style: "Body1"
                    font_size: 10
                    size_hint_x: 0.12
                MDLabel:
                    elevation: 3
                    id: xrp_address
                    font_style: "Body1"
                    font_size: 12
                    size_hint_x: 0.88
                    halign: "center"
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: amount_calorietest_input
                multiline: False
                input_filter: 'float'
                input_filter_min: 0
                input_filter_max: 999999999999.999999
                hint_text: 'Amount (CalorieTest)'
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: destination_input
                multiline: False
                hint_text: 'Destination Address'
            MDLabel:
                size_hint: (1, .1)
            MDGridLayout:
                size_hint: (1, .4)
                cols:3

                MDLabel:
                    size_hint: (.35, 1)
                MDFillRoundFlatIconButton:
                    size_hint: (.3, 1)
                    icon: "send"
                    theme_icon_color: "Custom"
                    icon_color: rgba('#505CA9')
                    text:"Send CalorieTest"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (.6, 1)
                    on_press: root.send_calorietest()
                MDLabel:
                    size_hint: (.35, 1)
            MDLabel:
                size_hint: (1, .4)
            MDGridLayout:
                size_hint: (1, .5)
                cols:3

                MDLabel:
                    size_hint: (.22, 1)
                    text: "CalorieTest"
                    theme_text_color: "Custom"
                    text_color: rgba('#202443')
                    halign: 'center'
                    font_size: 11
                    theme_text_color: "Primary"
                MDLabel:
                    size_hint: (.56, 1)
                    id: calorietest_balance
                    font_style: "Body1"
                    halign: "center"
                    theme_text_color: "Custom"
                    text_color: "green"
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                MDLabel:
                    size_hint: (.22, 1)
            MDLabel:
                size_hint: (1, .5)
                text: "Transactions"
                halign: "center"
                font_size: 12
                theme_text_color: "Primary"
            MDScrollView:
                size_hint: (1, 2)
                do_scroll_x: False
                do_scroll_y: True
                bar_color: rgba ('#f9b233')
                MDGridLayout:
                    cols: 1
                    padding: 10
                    spacing: 25
                    size_hint: None, None
                    width: 500
                    height: self.minimum_height
                    canvas.before:
                        Color:
                            rgba: rgba('#dadeed')
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction1
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction2
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction3
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction4
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction5
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction6
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction7
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction8
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction9
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction10
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction11
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction12
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction13
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction14
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction15
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction16
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction17
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction18
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction19
                        font_size: 11
                        theme_text_color: "Primary"
                    MDLabel:
                        size_hint: (1, .05)
                        id: transaction20
                        font_size: 11
                        theme_text_color: "Primary"
            MDLabel:
                size_hint: (1, 1.5)
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.backto_wallet()]]

<NFTMintScreen>
    uri: uri
    taxon: taxon
    input_error: input_error

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)
            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)
            MDLabel:
                size_hint: (1, .05)
            MDGridLayout:
                size_hint: (1, .1)
                cols:4
                MDLabel:
                    size_hint: (.2, 1)
                MDGridLayout:
                    size_hint: (.05, 1)
                    rows:2
                    MDIcon:
                        icon: "brush"
                        theme_text_color: "Custom"
                        text_color: rgba('#008D36')
                        icon_size: "16sp"
                        size_hint: (1, .95)
                    MDLabel:
                        size_hint: (1, .05)
                MDGridLayout:
                    size_hint: (.5, 1)
                    rows:2

                    MDLabel:
                        size_hint: (1, .6)
                        text: "NFT Minter"
                        theme_text_color: "Custom"
                        text_color: rgba('#202443')
                        halign: 'center'
                        font_size: '22sp'
                    MDLabel:
                        size_hint: (1, .4)


                MDLabel:
                    size_hint: (.25, 1)
            MDLabel:
                size_hint: (1, .06)
            MDGridLayout:
                size_hint: (1, .14)
                cols:3
                MDLabel:
                    size_hint: (.25, 1)
                    text: "Enter URI Link"
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    size_hint: (.7, 1)
                    id: uri
                    multiline:False
                MDLabel:
                    size_hint: (.05, 1)
            MDLabel:
                size_hint: (1, 0.05)
            MDGridLayout:
                size_hint: (1, .14)
                cols:3

                MDLabel:
                    size_hint: (.25, 1)
                    text: "Enter Taxon"
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    size_hint: (.7, 1)
                    id: taxon
                    multiline:False
                MDLabel:
                    size_hint: (.05, 1)
            MDLabel:
                size_hint: (1, .05)
            MDGridLayout:
                cols:3
                size_hint: (1, .1)
                MDLabel:
                    size_hint: (.33, 1)
                MDFillRoundFlatIconButton:
                    icon: "brush"
                    theme_icon_color: "Custom"
                    icon_color: rgba('#505CA9')
                    text:"Mint NFT"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (.6, 1)
                    on_press: root.mint()
                MDLabel:
                    size_hint: (.33, 1)
            MDLabel:
                size_hint: (1, 0.06)
            MDLabel:
                size_hint: (1, .05)
                id: input_error
                font_style: "Body1"
                halign: "center"
                theme_text_color: "Primary"
            MDLabel:
                size_hint: (1, .24)
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["menu", lambda x: nav_drawer.set_state('toggle')]]
    MDNavigationDrawer:
        md_bg_color: rgba('#b6bedb')
        id: nav_drawer
        radius: (0, 16, 16, 0)

        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "CalorieApp"
                title_color: "#202443"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                icon: "wallet"
                text: "Wallet"
                on_press:
                    root.walletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "brush"
                text: "NFT Minter"
                on_press:
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "wallet-plus"
                text: "Create/Import Wallet"
                on_press:
                    root.createimportwalletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "arrow-left-right-bold-outline"
                text: "DEX Trade"
                on_press:
                    root.dextradescreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "food"
                text: "Food Tracker"
                on_press:
                    root.foodtrackscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "application-settings"
                text: "Settings"
                on_press:
                    root.settingsscreen()
                    nav_drawer.set_state("close")

<CreateImportWalletScreen>
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Create/Import Wallet"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
                size_hint: (1, .2)

            MDLabel:
                size_hint: (1, .1)

            MDGridLayout:
                cols:3
                size_hint: (1, .15)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "wallet-plus"
                    text:"Create wallet"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.create_extrawallet_screen()
                MDLabel:
                    size_hint: (4, 1)

            MDLabel:
                size_hint: (1, .1)

            MDGridLayout:
                cols:3
                size_hint: (1, .15)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "wallet"
                    text:"Import wallet"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.import_extrawallet_screen()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
                size_hint: (1, .3)

        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["menu", lambda x: nav_drawer.set_state('toggle')]]
    
    MDNavigationDrawer:
        md_bg_color: rgba('#b6bedb')
        id: nav_drawer
        radius: (0, 16, 16, 0)

        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "CalorieApp"
                title_color: "#202443"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                icon: "wallet"
                text: "Wallet"
                on_press:
                    root.walletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "brush"
                text: "NFT Minter"
                on_press:
                    root.nftmintscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "wallet-plus"
                text: "Create/Import Wallet"
                on_press:
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "arrow-left-right-bold-outline"
                text: "DEX Trade"
                on_press:
                    root.dextradescreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "food"
                text: "Food Tracker"
                on_press:
                    root.foodtrackscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "application-settings"
                text: "Settings"
                on_press:
                    root.settingsscreen()
                    nav_drawer.set_state("close")

<DEXTradeScreen>
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "DEX Trade\nUnder Development"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
                halign: 'center'
                font_size: '22sp'
            MDLabel:
            MDLabel:
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["menu", lambda x: nav_drawer.set_state('toggle')]]
    MDNavigationDrawer:
        md_bg_color: rgba('#b6bedb')
        id: nav_drawer
        radius: (0, 16, 16, 0)

        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "CalorieApp"
                title_color: "#202443"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                icon: "wallet"
                text: "Wallet"
                on_press:
                    root.walletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "brush"
                text: "NFT Minter"
                on_press:
                    root.nftmintscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "wallet-plus"
                text: "Create/Import Wallet"
                on_press:
                    root.createimportwalletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "arrow-left-right-bold-outline"
                text: "DEX Trade"
                on_press:
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "food"
                text: "Food Tracker"
                on_press:
                    root.foodtrackscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "application-settings"
                text: "Settings"
                on_press:
                    root.settingsscreen()
                    nav_drawer.set_state("close")

<FoodTrackScreen>
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Food Tracking\nUnder Development"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
                halign: 'center'
                font_size: '22sp'
            MDLabel:
            MDLabel:
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["menu", lambda x: nav_drawer.set_state('toggle')]]
    MDNavigationDrawer:
        md_bg_color: rgba('#b6bedb')
        id: nav_drawer
        radius: (0, 16, 16, 0)

        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "CalorieApp"
                title_color: "#202443"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                icon: "wallet"
                text: "Wallet"
                on_press:
                    root.walletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "brush"
                text: "NFT Minter"
                on_press:
                    root.nftmintscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "wallet-plus"
                text: "Create/Import Wallet"
                on_press:
                    root.createimportwalletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "arrow-left-right-bold-outline"
                text: "DEX Trade"
                on_press:
                    root.dextradescreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "food"
                text: "Food Tracker"
                on_press:
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "application-settings"
                text: "Settings"
                on_press:
                    root.settingsscreen()
                    nav_drawer.set_state("close")

<SettingsScreen>
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Settings\nUnder Development"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
                halign: 'center'
                font_size: '22sp'
            MDLabel:
            MDLabel:
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["menu", lambda x: nav_drawer.set_state('toggle')]]
    MDNavigationDrawer:
        md_bg_color: rgba('#b6bedb')
        id: nav_drawer
        radius: (0, 16, 16, 0)

        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "CalorieApp"
                title_color: "#202443"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                icon: "wallet"
                text: "Wallet"
                on_press:
                    root.walletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "brush"
                text: "NFT Minter"
                on_press:
                    root.nftmintscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "wallet-plus"
                text: "Create/Import Wallet"
                on_press:
                    root.createimportwalletscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "arrow-left-right-bold-outline"
                text: "DEX Trade"
                on_press:
                    root.dextradescreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "food"
                text: "Food Tracker"
                on_press:
                    root.foodtrackscreen()
                    nav_drawer.set_state("close")
            DrawerClickableItem:
                icon: "application-settings"
                text: "Settings"
                on_press:
                    nav_drawer.set_state("close")

<IntroScreen>:
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                font_style: "H5"
                text: "Welcome to the CalorieApp"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDLabel:
                text: "Track your Calories"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDLabel:
                text: "Calorie aims to be the world’s food token"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "page-next-outline"
                    text:"Next"
                    theme_icon_color: "Custom"
                    icon_color: rgba('#505CA9')
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.next()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"

<FirstUseScreen>:
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)
            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)
            MDLabel:
            MDLabel:
                text: "Create a password for your account"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDLabel:
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: password
                hint_text: "Enter your password"
                font_style: "Body1"
                helper_text: "Password will be used to encrypt your private keys."
                helper_text_mode: "on_focus"
            MDLabel:
            MDTextField:
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: confirm_password
                hint_text: "Confirm your password"
                font_style: "Body1"
                helper_text: "Re-enter your password."
                helper_text_mode: "on_focus"
            MDLabel:
            MDGridLayout:
                cols:3
                size_hint: (1, .2)
                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "lock-check"
                    text:"Create Password"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.create_password()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
            MDLabel:
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)
            MDTopAppBar:
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"

<ImportKeysScreen>:
    invalid_keys: invalid_keys

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Import your XRPL wallet"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Public key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: public_key
                    font_style: "Body1"
                    halign: "center"
                    size_hint_x: 0.8
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Private key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: private_key
                    font_style: "Body1"
                    size_hint_x: 0.8

            MDLabel:
            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)

                MDLabel:
                    size_hint: (4, 1)

            MDLabel:

            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "lock-check"
                    text:"Store keys"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.store_keys()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
                id: invalid_keys
                font_style: "Body1"
                halign: "center"
                theme_text_color: "Primary"
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.go_back()]]

<ImportExtraKeysScreen>:
    invalid_keys: invalid_keys

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Import your XRPL wallet"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Public key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: public_key
                    font_style: "Body1"
                    halign: "center"
                    size_hint_x: 0.8
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Private key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: private_key
                    font_style: "Body1"
                    size_hint_x: 0.8

            MDLabel:
            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)

                MDLabel:
                    size_hint: (4, 1)

            MDLabel:

            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "lock-check"
                    text:"Store keys"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.store_keys()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
                id: invalid_keys
                font_style: "Body1"
                halign: "center"
                theme_text_color: "Primary"
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.go_back()]]

<CreateWalletScreen>:
    invalid_keys: invalid_keys

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Generate your XRPL wallet"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Public key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: public_key
                    font_style: "Body1"
                    halign: "center"
                    size_hint_x: 0.8
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Private key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: private_key
                    font_style: "Body1"
                    size_hint_x: 0.8

            MDLabel:
            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "wallet-plus"
                    text:"Generate keys"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.generate_keys()
                MDLabel:
                    size_hint: (4, 1)

            MDLabel:

            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "lock-check"
                    text:"Store keys"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.store_keys()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
                id: invalid_keys
                font_style: "Body1"
                halign: "center"
                theme_text_color: "Primary"
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.go_back()]]

<CreateExtraWalletScreen>:
    invalid_keys: invalid_keys

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Generate your XRPL wallet"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Public key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: public_key
                    font_style: "Body1"
                    halign: "center"
                    size_hint_x: 0.8
            MDBoxLayout:
                orientation: "horizontal"
                MDLabel:
                    text: "Private key:"
                    font_style: "Body1"
                    size_hint_x: 0.2
                MDTextField:
                    mode: "fill"
                    line_color_focus: rgba('#008D36')
                    hint_text_color_focus: rgba('#008D36')
                    fill_color_normal: rgba('#dadeed')
                    fill_color_focus: rgba('e9ebf5')
                    id: private_key
                    font_style: "Body1"
                    size_hint_x: 0.8

            MDLabel:
            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "wallet-plus"
                    text:"Generate keys"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.generate_keys()
                MDLabel:
                    size_hint: (4, 1)

            MDLabel:

            MDGridLayout:
                cols:3
                size_hint: (1, .2)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "lock-check"
                    text:"Store keys"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.store_keys()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
                id: invalid_keys
                font_style: "Body1"
                halign: "center"
                theme_text_color: "Primary"
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                specific_text_color: rgba('#f9b233')
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"
                left_action_items: [["arrow-u-left-top-bold", lambda x: root.go_back()]]

<WalletSetupScreen>:   
    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
                text: "Wallet Setup"
                font_style: "H5"
                halign: "center"
                theme_text_color: "Custom"
                text_color: rgba('#202443')
                size_hint: (1, .2)

            MDLabel:
                size_hint: (1, .1)

            MDGridLayout:
                cols:3
                size_hint: (1, .15)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "wallet-plus"
                    text:"Create wallet"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.create_wallet_screen()
                MDLabel:
                    size_hint: (4, 1)

            MDLabel:
                size_hint: (1, .1)

            MDGridLayout:
                cols:3
                size_hint: (1, .15)

                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "wallet"
                    text:"Import wallet"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (2, 1)
                    on_press: root.import_wallet_screen()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
                size_hint: (1, .3)

        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"

<LoginScreen>:
    password: password

    MDBoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: rgba('#bfc6e0')
            Rectangle:
                pos: self.pos
                size: self.size
        MDGridLayout:
            cols:3
            size_hint: (1, .12)

            MDLabel:
                size_hint: (.03, 1)
            MDTopAppBar:
                title: "CalorieApp"
                size_hint: (.67, 1)
                specific_text_color: rgba('#b6bedb')
                md_bg_color: rgba('#505CA9')
            Image:
                size_hint: (.3, 1)
                source: 'Images/CalorieLogoTranspa.png'
                mipmap: True
        MDGridLayout:
            cols:1
            size_hint: (1, .75)

            MDLabel:
            MDTextField:
                password: True
                mode: "fill"
                line_color_focus: rgba('#008D36')
                hint_text_color_focus: rgba('#008D36')
                fill_color_normal: rgba('#dadeed')
                fill_color_focus: rgba('e9ebf5')
                id: password
                hint_text: "Enter your password"
                font_style: "Body1"
            MDLabel:
                id: error_label
                text: ""
                color: 1, 0, 0, 1
            MDGridLayout:
                cols:3
                size_hint: (1, .2)
                MDLabel:
                    size_hint: (4, 1)
                MDFillRoundFlatIconButton:
                    icon: "login"
                    theme_icon_color: "Custom"
                    icon_color: rgba('#505CA9')
                    text:"Login"
                    md_bg_color: rgba('#f9b233')
                    text_color: rgba('#008D36')
                    size_hint: (.6, 1)
                    on_press: root.login()
                MDLabel:
                    size_hint: (4, 1)
            MDLabel:
        MDBottomAppBar:
            md_bg_color: rgba('#505CA9')
            size_hint: (1, .03)

            MDTopAppBar:
                icon: "Images\CalorieAppLogoTranspa.png"
                icon_color: rgba('#b6bedb')
                type: "bottom"